[workspace]
members = [
    # bitmatch
    "bitmatch",
    "bitmatch/macros",
    # emulator core files.
    "core/core-util",
    "core/*",
    # emulator frontend files.
    "frontend/*"
]
# Required to determine version for wgpu
resolver = "2"
